### ISSUE TITLE
Crashes when opened from widget

### ISSUE THREAD

**Issue by rugk** [tom-anders/Easy_xkcd#110]
The app is shown shortly, but afterwards crashes.
```
D/AndroidRuntime( 9370): Shutting down VM
E/AndroidRuntime( 9370): FATAL EXCEPTION: main
E/AndroidRuntime( 9370): Process: de.tap.easy_xkcd, PID: 9370
E/AndroidRuntime( 9370): Theme: themes:{com.android.providers.downloads.ui=overlay:com.spastef.inversion, com.fsck.k9=overlay:com.chummy.jezebel.material.dark.regression, default=overlay:com.chummy.jezebel.material.dark.regression, iconPack:system, fontPkg:com.chummy.jezebel.material.dark, com.android.systemui=overlay:com.chummy.jezebel.material.dark.regression, com.android.systemui.navbar=overlay:com.chummy.jezebel.material.dark.regression}
E/AndroidRuntime( 9370): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/AndroidRuntime( 9370): 	at de.tap.easy_xkcd.fragments.comics.ComicFragment$ComicAdapter.<init>(ComicFragment.java:134)
E/AndroidRuntime( 9370): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$ComicBrowserPagerAdapter.<init>(ComicBrowserFragment.java:193)
E/AndroidRuntime( 9370): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:167)
E/AndroidRuntime( 9370): 	at de.tap.easy_xkcd.fragments.comics.ComicBrowserFragment$updateNewest.onPostExecute(ComicBrowserFragment.java:125)
E/AndroidRuntime( 9370): 	at android.os.AsyncTask.finish(AsyncTask.java:651)
E/AndroidRuntime( 9370): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E/AndroidRuntime( 9370): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
E/AndroidRuntime( 9370): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9370): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime( 9370): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/AndroidRuntime( 9370): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9370): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime( 9370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime( 9370): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

After the crash the widget is empty. (Which is also not nice)

CM 13

**Comment by tom-anders** [comment]
Should probably be resolved in v8.0 (rewrite in Kotlin, so NullPointerExceptions shouldn't happen anymore)
