### ISSUE TITLE
Comic 2235 crahes app

### ISSUE THREAD

**Issue by JonnyTech** [tom-anders/Easy_xkcd#177]
Log:

```
LOGCAT=11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.915 E/AndroidRuntime(10249): at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:821)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.View.draw(View.java:19392)
11-29 19:14:39.915 E/AndroidRuntime(10249): at com.android.internal.policy.DecorView.draw(DecorView.java:807)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.View.updateDisplayListIfDirty(View.java:18287)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewRootImpl.draw(ViewRootImpl.java:3380)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3182)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2703)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1602)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7407)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:948)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.Choreographer.doCallbacks(Choreographer.java:750)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.Choreographer.doFrame(Choreographer.java:682)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:934)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.os.Handler.handleCallback(Handler.java:869)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.os.Handler.dispatchMessage(Handler.java:101)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.os.Looper.loop(Looper.java:206)
11-29 19:14:39.915 E/AndroidRuntime(10249): at android.app.ActivityThread.main(ActivityThread.java:6733)
11-29 19:14:39.915 E/AndroidRuntime(10249): at java.lang.reflect.Method.invoke(Native Method)
11-29 19:14:39.915 E/AndroidRuntime(10249): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11-29 19:14:39.915 E/AndroidRuntime(10249): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
11-29 19:14:39.916 E/ACRA    (10249): ACRA caught a RuntimeException for de.tap.easy_xkcd
11-29 19:14:39.916 E/ACRA    (10249): java.lang.RuntimeException: Canvas: trying to draw too large(218555296bytes) bitmap.
11-29 19:14:39.916 E/ACRA    (10249): at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
11-29 19:14:39.916 E/ACRA    (10249): at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
11-29 19:14:39.916 E/ACRA    (10249): at android.widget.ImageView.onDraw(ImageView.java:1367)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19380)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18287)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18237)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18237)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18237)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19392)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18287)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18275)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19092)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
11-29 19:14:39.916 E/ACRA    (10249): at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:821)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.draw(View.java:19392)
11-29 19:14:39.916 E/ACRA    (10249): at com.android.internal.policy.DecorView.draw(DecorView.java:807)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.View.updateDisplayListIfDirty(View.java:18287)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewRootImpl.draw(ViewRootImpl.java:3380)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3182)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2703)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1602)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7407)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:948)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.Choreographer.doCallbacks(Choreographer.java:750)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.Choreographer.doFrame(Choreographer.java:682)
11-29 19:14:39.916 E/ACRA    (10249): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:934)
11-29 19:14:39.916 E/ACRA    (10249): at android.os.Handler.handleCallback(Handler.java:869)
11-29 19:14:39.916 E/ACRA    (10249): at android.os.Handler.dispatchMessage(Handler.java:101)
11-29 19:14:39.916 E/ACRA    (10249): at android.os.Looper.loop(Looper.java:206)
11-29 19:14:39.916 E/ACRA    (10249): at android.app.ActivityThread.main(ActivityThread.java:6733)
11-29 19:14:39.916 E/ACRA    (10249): at java.lang.reflect.Method.invoke(Native Method)
11-29 19:14:39.916 E/ACRA    (10249): at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11-29 19:14:39.916 E/ACRA    (10249): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
USER_COMMENT=
ANDROID_VERSION=8.0.0
STACK_TRACE=java.lang.RuntimeException: Canvas: trying to draw too large(218555296bytes) bitmap.
at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
at android.widget.ImageView.onDraw(ImageView.java:1367)
at android.view.View.draw(View.java:19380)
at android.view.View.updateDisplayListIfDirty(View.java:18287)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
at android.view.View.updateDisplayListIfDirty(View.java:18237)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
at android.view.View.updateDisplayListIfDirty(View.java:18237)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4324)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4304)
at android.view.View.updateDisplayListIfDirty(View.java:18237)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.draw(View.java:19392)
at android.view.View.updateDisplayListIfDirty(View.java:18287)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at android.view.View.updateDisplayListIfDirty(View.java:18275)
at android.view.View.draw(View.java:19092)
at android.view.ViewGroup.drawChild(ViewGroup.java:4340)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4126)
at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:821)
at android.view.View.draw(View.java:19392)
at com.android.internal.policy.DecorView.draw(DecorView.java:807)
at android.view.View.updateDisplayListIfDirty(View.java:18287)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3380)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3182)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2703)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1602)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7407)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:948)
at android.view.Choreographer.doCallbacks(Choreographer.java:750)
at android.view.Choreographer.doFrame(Choreographer.java:682)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:934)
at android.os.Handler.handleCallback(Handler.java:869)
at android.os.Handler.dispatchMessage(Handler.java:101)
at android.os.Looper.loop(Looper.java:206)
at android.app.ActivityThread.main(ActivityThread.java:6733)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

PHONE_MODEL=TA-1020
APP_VERSION_NAME=7.3.6
PACKAGE_NAME=de.tap.easy_xkcd
SHARED_PREFERENCES=default.transcripts_fixed=true
default.pref_zoom_scroll=true
default.pref_custom_tabs=true
default.pref_offline=true
default.pref_mobile=false
default.pref_share=false
default.pref_alt_options=[pref_alt]
default.pref_include_link=false
default.pref_fullscreen_enabled=true
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.pref_notifications=0
default.pref_nav_swipe=true
default.pref_doubletap=false
default.pref_alt_activation=1
default.pref_offline_whatif=true
default.cache_fixed_7.3.3=true
default.pref_overview_default=false
default.pref_zoom=default
default.cache_fixed_7.3.4=true
default.cache_fixed_7.3.6=true
default.pref_update_mobile=false
default.pref_night=true
default.pref_large=true
default.pref_alt_style_new=1
default.pref_default_zoom=true
default.acra.lastVersionNr=163
```

**Comment by tom-anders** [comment]
Looks like Randall accidentally posted a image with insanely high resolution. But it looks like this has already been fixed, does it still crash for you?

**Comment by JonnyTech** [comment]
After force stopping and clearing cache, all is good now - thanks for checking.

**Comment by JonnyTech** [comment]
Is there any way to error trap this for the future?

**Comment by tom-anders** [comment]
Probably, but I'm not sure at which point in the code this exception is actually thrown. You can take a look if you want, of course
