### ISSUE TITLE
App crashes when opening What-If section

### ISSUE THREAD

**Issue by paulusasol** [tom-anders/Easy_xkcd#258]
Expected behaviour: What-If section opens normally or shows an error message if something fails.
Observed behaviour: The App claims to be loading new articles, before crashing.
App Version: 7.3.9 from F-Droid
Crash info:
```
APP_VERSION_NAME=7.3.9
LOGCAT=05-18 19:07:37.158 W/System.err(18933): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-18 19:07:37.158 W/System.err(18933): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
05-18 19:07:37.158 W/System.err(18933): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
05-18 19:07:37.159 W/System.err(18933): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-18 19:07:37.160 W/System.err(18933): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
05-18 19:07:37.160 W/System.err(18933): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-18 19:07:37.160 W/System.err(18933): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
05-18 19:07:37.160 W/System.err(18933): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
05-18 19:07:37.160 W/System.err(18933): 	at okhttp3.RealCall.execute(RealCall.java:77)
05-18 19:07:37.160 W/System.err(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfOverviewFragment$GetDoc.doInBackground(WhatIfOverviewFragment.java:170)
05-18 19:07:37.160 W/System.err(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfOverviewFragment$GetDoc.doInBackground(WhatIfOverviewFragment.java:150)
05-18 19:07:37.160 W/System.err(18933): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-18 19:07:37.161 W/System.err(18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-18 19:07:37.161 W/System.err(18933): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-18 19:07:37.161 W/System.err(18933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-18 19:07:37.161 W/System.err(18933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-18 19:07:37.161 W/System.err(18933): 	at java.lang.Thread.run(Thread.java:919)
05-18 19:07:37.161 W/System.err(18933): Caused by: java.net.ConnectException: failed to connect to what-if.xkcd.com/151.101.112.67 (port 443) from /10.[Redacted without reason] (port 39674) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
05-18 19:07:37.161 W/System.err(18933): 	at libcore.io.IoBridge.isConnected(IoBridge.java:288)
05-18 19:07:37.161 W/System.err(18933): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:193)
05-18 19:07:37.161 W/System.err(18933): 	at libcore.io.IoBridge.connect(IoBridge.java:135)
05-18 19:07:37.161 W/System.err(18933): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
05-18 19:07:37.161 W/System.err(18933): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
05-18 19:07:37.161 W/System.err(18933): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
05-18 19:07:37.161 W/System.err(18933): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
05-18 19:07:37.161 W/System.err(18933): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
05-18 19:07:37.162 W/System.err(18933): 	at java.net.Socket.connect(Socket.java:621)
05-18 19:07:37.162 W/System.err(18933): 	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
05-18 19:07:37.162 W/System.err(18933): 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
05-18 19:07:37.162 W/System.err(18933): 	... 25 more
05-18 19:07:37.162 W/System.err(18933): Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
05-18 19:07:37.162 W/System.err(18933): 	at libcore.io.IoBridge.isConnected(IoBridge.java:275)
05-18 19:07:37.162 W/System.err(18933): 	... 35 more
05-18 19:07:37.182 E/AndroidRuntime(18933): FATAL EXCEPTION: AsyncTask #3
05-18 19:07:37.182 E/AndroidRuntime(18933): Process: de.tap.easy_xkcd, PID: 18933
05-18 19:07:37.182 E/AndroidRuntime(18933): java.lang.RuntimeException: An error occurred while executing doInBackground()
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.lang.Thread.run(Thread.java:919)
05-18 19:07:37.182 E/AndroidRuntime(18933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:259)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:247)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-18 19:07:37.182 E/AndroidRuntime(18933): 	... 4 more
05-18 19:07:37.182 E/ACRA    (18933): ACRA caught a RuntimeException for de.tap.easy_xkcd
05-18 19:07:37.182 E/ACRA    (18933): java.lang.RuntimeException: An error occurred while executing doInBackground()
05-18 19:07:37.182 E/ACRA    (18933): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-18 19:07:37.182 E/ACRA    (18933): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.lang.Thread.run(Thread.java:919)
05-18 19:07:37.182 E/ACRA    (18933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
05-18 19:07:37.182 E/ACRA    (18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:259)
05-18 19:07:37.182 E/ACRA    (18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:247)
05-18 19:07:37.182 E/ACRA    (18933): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-18 19:07:37.182 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-18 19:07:37.182 E/ACRA    (18933): 	... 4 more
05-18 19:07:37.202 E/AndroidRuntime(18933): FATAL EXCEPTION: AsyncTask #4
05-18 19:07:37.202 E/AndroidRuntime(18933): Process: de.tap.easy_xkcd, PID: 18933
05-18 19:07:37.202 E/AndroidRuntime(18933): java.lang.RuntimeException: An error occurred while executing doInBackground()
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.lang.Thread.run(Thread.java:919)
05-18 19:07:37.202 E/AndroidRuntime(18933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFavoritesFragment$DisplayOverview.doInBackground(WhatIfFavoritesFragment.java:85)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFavoritesFragment$DisplayOverview.doInBackground(WhatIfFavoritesFragment.java:66)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-18 19:07:37.202 E/AndroidRuntime(18933): 	... 4 more
05-18 19:07:37.202 E/ACRA    (18933): ACRA caught a RuntimeException for de.tap.easy_xkcd
05-18 19:07:37.202 E/ACRA    (18933): java.lang.RuntimeException: An error occurred while executing doInBackground()
05-18 19:07:37.202 E/ACRA    (18933): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-18 19:07:37.202 E/ACRA    (18933): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.lang.Thread.run(Thread.java:919)
05-18 19:07:37.202 E/ACRA    (18933): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
05-18 19:07:37.202 E/ACRA    (18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFavoritesFragment$DisplayOverview.doInBackground(WhatIfFavoritesFragment.java:85)
05-18 19:07:37.202 E/ACRA    (18933): 	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFavoritesFragment$DisplayOverview.doInBackground(WhatIfFavoritesFragment.java:66)
05-18 19:07:37.202 E/ACRA    (18933): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
05-18 19:07:37.202 E/ACRA    (18933): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-18 19:07:37.202 E/ACRA    (18933): 	... 4 more
05-18 19:07:37.210 E/RecyclerView(18933): No adapter attached; skipping layout
PHONE_MODEL=[redacted]
PACKAGE_NAME=de.tap.easy_xkcd
ANDROID_VERSION=10
SHARED_PREFERENCES=default.transcripts_fixed=true
default.pref_zoom_scroll=true
default.pref_custom_tabs=true
default.pref_detect_color=true
default.pref_offline=true
default.pref_mobile=false
default.pref_share=false
default.pref_alt_options=[pref_alt]
default.widget_comicNumber=true
default.pref_include_link=false
default.pref_fullscreen_enabled=true
default.acra.legacyAlreadyConvertedTo4.8.0=true
default.pref_notifications=1
default.pref_nav_swipe=true
default.widget_alt=true
default.pref_doubletap=false
default.pref_alt_activation=1
default.pref_offline_whatif=false
default.pref_amoled=false
default.pref_overview_default=false
default.pref_zoom=default
default.cache_fixed_7.3.6=true
default.pref_update_mobile=true
default.pref_invert=true
default.pref_night=true
default.pref_large=true
default.pref_alt_style_new=1
default.pref_default_zoom=true
default.acra.lastVersionNr=166


STACK_TRACE=java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:259)
	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:247)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Document.select(java.lang.String)' on a null object reference
	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:259)
	at de.tap.easy_xkcd.fragments.whatIf.WhatIfFragment$DisplayOverview.doInBackground(WhatIfFragment.java:247)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

BRAND=[redacted]
```

**Comment by tom-anders** [comment]
I’m actually currently working on almost completely rewriting the handling of the WhatIf database. I’ll probably do it as beta release on Google Play, but I’ll try to also provide an app under the GitHub releases section, so that F-Droid users are able to test it as well.

**Comment by tom-anders** [comment]
Closing this as the beta is released now and should fix this issue
